# Generated by Django 3.1.4 on 2020-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10, null=True)),
                ('branch', models.CharField(max_length=20, null=True)),
                ('language', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
