# Generated by Django 3.1.4 on 2020-12-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobileno',
        ),
    ]
