# Generated by Django 3.1.4 on 2020-12-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_auto_20201214_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
